# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://pssguy.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: myTinyShinys

# Short description of your site
description: Business site. Creating interactive web apps and general R training

# Team names, titles and social links
people:
- name: Jenny Bryan
  pic: jenny
  position: Associate - Educator  
  Lots more stuff'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Andrew Clark
  pic: OliverHardy2
  position: Owner
  social:
    - title: twitter
      url: https://twitter.com/pssGuy
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/andrew-clark-23541727

- name: Dean Attali
  pic: dean
  position: Associate - Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
  
  # --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""


# Build settings
markdown: kramdown
permalink: pretty
